name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      -
        name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      -
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: coverage.out
          flags: unittests
